version: '3'
services:
  web-app:
    build:
      context: .
      dockerfile: Dockerfile_Rasul
    ports:
      - "8080:8080"
    depends_on:
      - db-server
    environment:
      DB_HOST: db-server
      DB_NAME: devops_lab
      DB_USER: devops
      DB_PASS: secretpassword

  db-server:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: devops_lab
      MYSQL_USER: devops
      MYSQL_PASSWORD: secretpassword
    ports:
      - "3307:3306"